#pragma once

#include "Platform/Platform.h"
#include "Platform/PlatformDevice.h"
#include "Platform/Input.h"

#include "Core/Container/Vector.h"
#include "Core/Container/Array.h"
#include "Core/Container/String.h"
#include "Core/Container/Blob.h"
#include "Core/Geometry.h"
#include "Core/Encoding.h"
#include "Core/Application.h"
#include "Core/View.h"
#include "Core/Config.h"
#include "Core/Physic.h"
#include "Core/Controller.h"
#include "Core/Event.h"
#include "Core/Worker/Job.h"
#include "Core/Worker/WorkerPool.h"
#include "Core/Worker/Worker.h"

#include "Memory/Memory.h"
#include "Memory/Pool.h"
#include "Memory/Allocator.h"
#include "Memory/Allocator/LinearAllocator.h"
#include "Memory/Allocator/PoolAllocator.h"

#include "Graphic/Compiler.h"
#include "Graphic/GraphicDevice.h"
#include "Graphic/Framebuffer.h"
#include "Graphic/DescriptorSet.h"
#include "Graphic/Buffer.h"
#include "Graphic/Texture.h"
#include "Graphic/Sampler.h"
#include "Graphic/Pipeline.h"
#include "Graphic/Program.h"
#include "Graphic/Shader.h"

#include "Audio/Audio.h"
#include "Audio/AudioStream.h"
#include "Audio/AudioDevice.h"

#include "OS/OS.h"
#include "OS/Logger.h"
#include "OS/Path.h"
#include "OS/Time.h"
#include "OS/Image.h"
#include "OS/Endian.h"
#include "OS/StopWatch.h"
#include "OS/Stream/MemoryStream.h"
#include "OS/Stream/FileStream.h"

#include "Scene/World.h"
#include "Scene/Entity.h"
#include "Scene/System.h"
#include "Scene/Component.h"

#include "Resource/Asset.h"
#include "Resource/AssetRegistry.h"
#include "Resource/AssetImporter.h"
#include "Resource/Resource.h"
#include "Resource/ResourceArchive.h"
#include "Resource/Resource/Font.h"
#include "Resource/Resource/Buffer.h"
#include "Resource/Resource/Texture.h"
#include "Resource/Resource/Sprite.h"
#include "Resource/Resource/Audio.h"
#include "Resource/Resource/StaticMesh.h"
#include "Resource/Resource/Material.h"


namespace aka {

};
